# docker compose file for projects frontend, backend - used for building images
# used by github actions (.github/workflows/main.yml)
# uses config file .env

version: '3.8'
name: car-demo

services:

  backend:
    # ak mame build a image zaroven, tak image sluzi na pomenovanie vytvoreneho image (defaultne vytvara car-demo-backend:latest)
    image: michalrakus/car-demo:backend-${IMAGE_VERSION}
    build: ../../backend

  frontend:
    # ak mame build a image zaroven, tak image sluzi na pomenovanie vytvoreneho image (defaultne vytvara car-demo-frontend:latest)
    image: michalrakus/car-demo:frontend-${IMAGE_VERSION}
    build:
      context: ../../frontend
      args:
        # these env variables must be also in frontend Dockerfile written (are needed during build (before run))
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_AUTH=${X_AUTH}
        - VITE_AUTH_OFF_USERNAME=${VITE_AUTH_OFF_USERNAME}
        - VITE_AUTH0_DOMAIN=${X_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_AUDIENCE=${X_AUTH0_AUDIENCE}
        #- BROWSER=none
