# Workflow build and deploy prod
name: Build and deploy prod

# workflow_dispatch umoznuje manualne spustanie cez button na github.com - dame zatial len manualne spustenie
#on: [push, workflow_dispatch]
on: [workflow_dispatch]
jobs:
  build-and-deploy-prod:
    name: Build and deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # prihlasime sa do Docker Hub (hub.docker.com) aby sme vedeli pushnut image do Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # nie je required ale je recommended
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image for backend
        run: |
          cd ./run-env/car-demo-prod
          docker compose -f docker-compose-build.yml build backend
          docker push michalrakus/car-demo:backend-1.0.0

      - name: Build and push image for frontend
        run: |
          cd ./run-env/car-demo-prod
          docker compose -f docker-compose-build.yml build frontend
          docker push michalrakus/car-demo:frontend-1.0.0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.ppk
          chmod 600 ~/.ssh/id_rsa.ppk
          cat >>~/.ssh/config <<END
          Host deploy-server
            HostName $SSH_HOST
            User $SSH_USERNAME
            IdentityFile ~/.ssh/id_rsa.ppk
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # poznamka ku docker pull - mohli by sme dat 1 prikaz: docker compose -f docker-compose-run.yml pull backend frontend
      # potom by vsak cislo verzie 1.0.0 tahal zo suboru .env a ten (momentalne) nekopirujeme automaticky z git-u, pouzivame kopiu na serveri,
      # preto by bola verzia neaktualna (pri push sa tiez pouziva cislo verzie "natvrdo" - pozri hore)
      # posledny prikaz: docker system prune -af -> remove unused images to free up space
      - name: Deploy
        run: |
          ssh deploy-server \
            'docker pull michalrakus/car-demo:backend-1.0.0 \
            && docker pull michalrakus/car-demo:frontend-1.0.0 \
            && cd /home/run-env/car-demo-prod \
            && docker compose -f docker-compose-run.yml up -d backend frontend \
            && docker system prune -af'
